export interface StateInfo {
  name: string;
  abbreviation: string;
  slug: string;
  emoji: string;
  lawName: string;
  lawYear: string;
  lawAcronym: string;
  badgeText: string;
  responseTimeDays: number;
  maxFine: string;
  population: string;
  rights: { title: string; description: string }[];
  topBrokers: { name: string; difficulty: string; time: string }[];
  stats: { stat: string; label: string }[];
  faqs: { question: string; answer: string }[];
  heroDescription: string;
  ctaText: string;
}

// Common brokers used across states
const BROKERS_SET_A = [
  { name: "Spokeo", difficulty: "Easy", time: "24-72 hours" },
  { name: "WhitePages", difficulty: "Medium", time: "48-72 hours" },
  { name: "BeenVerified", difficulty: "Easy", time: "24-48 hours" },
  { name: "Intelius", difficulty: "Medium", time: "72 hours" },
  { name: "Radaris", difficulty: "Hard", time: "7-30 days" },
  { name: "MyLife", difficulty: "Hard", time: "7-14 days" },
];

const BROKERS_SET_B = [
  { name: "PeopleFinder", difficulty: "Easy", time: "24-48 hours" },
  { name: "TruePeopleSearch", difficulty: "Easy", time: "24-72 hours" },
  { name: "FastPeopleSearch", difficulty: "Easy", time: "24-48 hours" },
  { name: "USSearch", difficulty: "Medium", time: "48-72 hours" },
  { name: "Spokeo", difficulty: "Easy", time: "24-72 hours" },
  { name: "Radaris", difficulty: "Hard", time: "7-30 days" },
];

const BROKERS_SET_C = [
  { name: "BeenVerified", difficulty: "Easy", time: "24-48 hours" },
  { name: "Intelius", difficulty: "Medium", time: "72 hours" },
  { name: "TruePeopleSearch", difficulty: "Easy", time: "24-72 hours" },
  { name: "WhitePages", difficulty: "Medium", time: "48-72 hours" },
  { name: "MyLife", difficulty: "Hard", time: "7-14 days" },
  { name: "PeopleFinder", difficulty: "Easy", time: "24-48 hours" },
];

// Federal rights for states without comprehensive privacy laws
const FEDERAL_RIGHTS = [
  { title: "Right to Dispute", description: "Under the Fair Credit Reporting Act (FCRA), you can dispute inaccurate information in your consumer reports" },
  { title: "Right to Opt-Out of Marketing", description: "The CAN-SPAM Act gives you the right to opt out of commercial email and the right to have opt-out requests honored" },
  { title: "Right to Stop Calls", description: "The Telephone Consumer Protection Act (TCPA) protects you from unwanted telemarketing calls and texts" },
  { title: "Right to Breach Notification", description: "State breach notification law requires companies to notify you if your personal data is compromised in a data breach" },
];

function federalFaqs(stateName: string): { question: string; answer: string }[] {
  return [
    {
      question: `What privacy laws protect ${stateName} residents?`,
      answer: `${stateName} residents are protected by federal privacy laws including the Fair Credit Reporting Act (FCRA), CAN-SPAM Act, Telephone Consumer Protection Act (TCPA), and ${stateName}'s data breach notification law. These provide baseline protections for data disputes, marketing opt-outs, and breach notifications.`,
    },
    {
      question: `Can I remove my data from data brokers in ${stateName}?`,
      answer: `Yes. While ${stateName} doesn't have a comprehensive state privacy law, you can still submit opt-out requests to data brokers under federal law and the broker's own policies. Most brokers honor removal requests regardless of your state of residence.`,
    },
    {
      question: `How long do data brokers have to respond to removal requests in ${stateName}?`,
      answer: `Under federal law, data brokers must respond to consumer disputes within 30 days. Most brokers process opt-out requests within 24 hours to 30 days depending on their internal processes.`,
    },
    {
      question: `What is the FCRA and how does it help me?`,
      answer: `The Fair Credit Reporting Act (FCRA) regulates consumer reporting agencies and gives you the right to access your data, dispute inaccuracies, and have errors corrected within 30 days.`,
    },
    {
      question: `Does ${stateName} have a data breach notification law?`,
      answer: `Yes, ${stateName} has a data breach notification law requiring companies to notify residents when their personal information is compromised. This ensures you're informed if your data is exposed.`,
    },
    {
      question: `How does GhostMyData help ${stateName} residents?`,
      answer: `GhostMyData automates opt-out requests to data brokers on behalf of ${stateName} residents. We scan 2,100+ brokers, submit removal requests, track responses, and monitor for re-listings — all automatically.`,
    },
  ];
}

function federalStats(population: string, brokerCount: string): { stat: string; label: string }[] {
  return [
    { stat: population, label: "State Residents" },
    { stat: brokerCount, label: "Data Brokers Active" },
    { stat: "Varies", label: "Federal Penalty Range" },
    { stat: "30 Days", label: "FCRA Response Time" },
  ];
}

function stateStats(population: string, brokerCount: string, maxFine: string, responseDays: string): { stat: string; label: string }[] {
  return [
    { stat: population, label: "State Residents" },
    { stat: brokerCount, label: "Data Brokers Active" },
    { stat: maxFine, label: "Max Violation Fine" },
    { stat: responseDays, label: "Required Response Time" },
  ];
}

export const STATE_DATA: Record<string, StateInfo> = {
  // ═══════════════════════════════════════════════════
  // EXISTING 10 STATES (porting current data)
  // ═══════════════════════════════════════════════════
  california: {
    name: "California",
    abbreviation: "CA",
    slug: "california",
    emoji: "🐻",
    lawName: "California Consumer Privacy Act",
    lawYear: "2018",
    lawAcronym: "CCPA",
    badgeText: "CCPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "39M+",
    rights: [
      { title: "Right to Know", description: "Request disclosure of what personal information businesses have collected about you" },
      { title: "Right to Delete", description: "Request deletion of personal information collected about you" },
      { title: "Right to Opt-Out", description: "Opt out of the sale or sharing of your personal information" },
      { title: "Right to Non-Discrimination", description: "Companies cannot discriminate against you for exercising your privacy rights" },
    ],
    topBrokers: BROKERS_SET_A,
    stats: stateStats("39M+", "500+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the CCPA?", answer: "The California Consumer Privacy Act (CCPA) is a state law that gives California residents greater control over their personal information. It requires businesses to disclose data collection practices and allows consumers to request deletion of their data." },
      { question: "Who is covered by the CCPA?", answer: "CCPA applies to California residents and businesses that collect personal information and meet certain thresholds (annual revenue over $25M, data on 100,000+ consumers, or 50%+ revenue from selling data)." },
      { question: "How long do companies have to respond to CCPA requests?", answer: "Businesses must respond to CCPA requests within 45 days. They can extend this by an additional 45 days if necessary, but must notify you of the extension." },
      { question: "Can I sue a company for CCPA violations?", answer: "Consumers can sue for data breaches resulting from a company's failure to maintain reasonable security. For other violations, you can file a complaint with the California Attorney General." },
      { question: "Does CCPA apply to data brokers?", answer: "Yes, data brokers are specifically covered under CCPA. California also requires data brokers to register with the state, making it easier to identify and submit removal requests." },
      { question: "How does GhostMyData help with CCPA compliance?", answer: "GhostMyData automates CCPA deletion requests to data brokers on your behalf, tracks responses, follows up on delayed requests, and provides documentation of your removal efforts." },
    ],
    heroDescription: "Exercise your California Consumer Privacy Act (CCPA) rights. GhostMyData helps California residents remove their personal information from data brokers.",
    ctaText: "Protect Your California Privacy Rights",
  },

  texas: {
    name: "Texas",
    abbreviation: "TX",
    slug: "texas",
    emoji: "⭐",
    lawName: "Texas Data Privacy and Security Act",
    lawYear: "2024",
    lawAcronym: "TDPSA",
    badgeText: "TDPSA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "30M+",
    rights: [
      { title: "Right to Access", description: "Confirm whether a controller is processing your personal data and access that data" },
      { title: "Right to Delete", description: "Request deletion of personal data you've provided" },
      { title: "Right to Opt-Out", description: "Opt out of the sale of personal data, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Request correction of inaccurate personal data" },
    ],
    topBrokers: BROKERS_SET_B,
    stats: stateStats("30M+", "450+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the TDPSA?", answer: "The Texas Data Privacy and Security Act (TDPSA) is a comprehensive privacy law that went into effect July 1, 2024. It gives Texas residents rights over their personal data held by businesses." },
      { question: "Who does the TDPSA apply to?", answer: "The TDPSA applies to businesses that conduct business in Texas or produce products/services consumed by Texas residents, and process or sell personal data." },
      { question: "How long do companies have to respond?", answer: "Companies must respond to consumer requests within 45 days, with a possible 45-day extension if reasonably necessary." },
      { question: "Can I opt out of data sales under TDPSA?", answer: "Yes, the TDPSA gives you the right to opt out of the sale of your personal data, targeted advertising, and certain profiling activities." },
      { question: "What penalties exist for TDPSA violations?", answer: "The Texas Attorney General can impose civil penalties of up to $7,500 per violation. There is no private right of action under TDPSA." },
      { question: "How does GhostMyData help Texas residents?", answer: "GhostMyData automates TDPSA-compliant deletion requests to data brokers on your behalf, tracks the 45-day response deadline, and follows up on non-compliant brokers." },
    ],
    heroDescription: "Exercise your Texas Data Privacy and Security Act (TDPSA) rights. GhostMyData helps Texas residents remove their personal information from data brokers.",
    ctaText: "Protect Your Texas Privacy Rights",
  },

  "new-york": {
    name: "New York",
    abbreviation: "NY",
    slug: "new-york",
    emoji: "🗽",
    lawName: "SHIELD Act",
    lawYear: "2020",
    lawAcronym: "SHIELD",
    badgeText: "SHIELD Protected",
    responseTimeDays: 30,
    maxFine: "$5,000",
    population: "19M+",
    rights: [
      { title: "Right to Security", description: "Businesses must implement reasonable safeguards to protect your private information" },
      { title: "Right to Notification", description: "Receive timely notification if your data is involved in a security breach" },
      { title: "Right to Dispute", description: "Challenge inaccurate information held by consumer reporting agencies under FCRA" },
      { title: "Right to Opt-Out", description: "Opt out of marketing communications and data broker listings" },
    ],
    topBrokers: BROKERS_SET_A,
    stats: stateStats("19M+", "500+", "$5,000", "30 Days"),
    faqs: [
      { question: "What is the NY SHIELD Act?", answer: "The Stop Hacks and Improve Electronic Data Security (SHIELD) Act broadens New York's data breach notification requirements and mandates reasonable data security safeguards." },
      { question: "Does New York have a comprehensive privacy law?", answer: "New York has the SHIELD Act for data security and breach notification. Additional comprehensive privacy legislation (NY Privacy Act) has been proposed but not yet enacted." },
      { question: "What are my rights under the SHIELD Act?", answer: "The SHIELD Act primarily protects you through mandatory data security standards and expanded breach notification requirements. Businesses must implement administrative, technical, and physical safeguards." },
      { question: "How does the SHIELD Act define private information?", answer: "The SHIELD Act broadly defines private information including social security numbers, driver's license numbers, financial account numbers, biometric data, and email/password combinations." },
      { question: "What penalties exist for SHIELD Act violations?", answer: "The NY Attorney General can seek injunctions and civil penalties up to $5,000 per violation for failure to notify, and up to $20 per failed notification (capped at $250,000)." },
      { question: "How does GhostMyData help New York residents?", answer: "GhostMyData scans 2,100+ data brokers for your personal information, automates removal requests, and provides ongoing monitoring to protect your privacy." },
    ],
    heroDescription: "Protect your privacy under New York's SHIELD Act. GhostMyData helps New York residents remove their personal information from data brokers.",
    ctaText: "Protect Your New York Privacy Rights",
  },

  florida: {
    name: "Florida",
    abbreviation: "FL",
    slug: "florida",
    emoji: "🌴",
    lawName: "Florida Digital Bill of Rights",
    lawYear: "2024",
    lawAcronym: "FDBR",
    badgeText: "FDBR Protected",
    responseTimeDays: 45,
    maxFine: "$50,000",
    population: "22M+",
    rights: [
      { title: "Right to Access", description: "Access the personal data that a controller has collected about you" },
      { title: "Right to Delete", description: "Request deletion of your personal data" },
      { title: "Right to Opt-Out", description: "Opt out of the sale of personal data and targeted advertising" },
      { title: "Right to Correct", description: "Correct inaccuracies in your personal data" },
    ],
    topBrokers: BROKERS_SET_C,
    stats: stateStats("22M+", "400+", "$50,000", "45 Days"),
    faqs: [
      { question: "What is the Florida Digital Bill of Rights?", answer: "The Florida Digital Bill of Rights (FDBR) is a comprehensive privacy law that went into effect July 1, 2024. It applies to large businesses and gives Florida residents control over their personal data." },
      { question: "Who does the FDBR apply to?", answer: "The FDBR applies to businesses with annual global revenue over $1 billion that conduct business in Florida and collect personal data. It has a higher threshold than most state privacy laws." },
      { question: "What makes Florida's law unique?", answer: "Florida's law specifically targets large tech companies and includes provisions about children's online safety. It also protects against government surveillance of online activities." },
      { question: "How long do companies have to respond?", answer: "Companies must respond to consumer requests within 45 days, with a possible extension of 15 additional days." },
      { question: "What are the penalties for violations?", answer: "The Florida Attorney General can impose civil penalties of up to $50,000 per violation, with treble damages for violations involving children's data." },
      { question: "How does GhostMyData help Florida residents?", answer: "GhostMyData automates data removal requests across 2,100+ brokers, tracks compliance with FDBR deadlines, and monitors for re-listings of your information." },
    ],
    heroDescription: "Exercise your Florida Digital Bill of Rights. GhostMyData helps Florida residents remove their personal information from data brokers.",
    ctaText: "Protect Your Florida Privacy Rights",
  },

  illinois: {
    name: "Illinois",
    abbreviation: "IL",
    slug: "illinois",
    emoji: "🏙️",
    lawName: "Biometric Information Privacy Act",
    lawYear: "2008",
    lawAcronym: "BIPA",
    badgeText: "BIPA Protected",
    responseTimeDays: 30,
    maxFine: "$5,000",
    population: "12M+",
    rights: [
      { title: "Biometric Privacy", description: "Companies must get informed consent before collecting your biometric data (fingerprints, face scans, etc.)" },
      { title: "Right to Know", description: "Be informed of the purpose and duration of biometric data collection" },
      { title: "Right to Sue", description: "Private right of action for BIPA violations — you can sue companies directly" },
      { title: "Data Protection", description: "Companies must store and protect biometric data using reasonable security measures" },
    ],
    topBrokers: BROKERS_SET_B,
    stats: stateStats("12M+", "400+", "$5,000", "30 Days"),
    faqs: [
      { question: "What is BIPA?", answer: "The Biometric Information Privacy Act (BIPA) is Illinois' landmark biometric privacy law. It requires informed consent for biometric data collection and provides a private right of action for violations." },
      { question: "What makes BIPA special?", answer: "BIPA is one of the strongest biometric privacy laws in the US because it allows individuals to sue companies directly for violations, unlike most other state privacy laws that rely on attorney general enforcement." },
      { question: "What counts as biometric data under BIPA?", answer: "BIPA covers fingerprints, voiceprints, face geometry scans, retina/iris scans, and other unique biological identifiers. It does not cover photographs, demographic data, or physical descriptions." },
      { question: "What are the penalties for BIPA violations?", answer: "BIPA allows damages of $1,000 per negligent violation and $5,000 per intentional/reckless violation, plus attorneys' fees. Several major class action settlements have exceeded $100 million." },
      { question: "Does Illinois have a general data privacy law?", answer: "Illinois has BIPA for biometric data and a data breach notification law. A comprehensive consumer privacy bill has been under consideration but not yet enacted." },
      { question: "How does GhostMyData help Illinois residents?", answer: "GhostMyData automates removal requests to data brokers, protecting Illinois residents' personal data. While BIPA covers biometric data specifically, we help remove all types of personal information from broker sites." },
    ],
    heroDescription: "Illinois leads the nation in biometric privacy protection with BIPA. GhostMyData helps Illinois residents remove their personal information from data brokers.",
    ctaText: "Protect Your Illinois Privacy Rights",
  },

  pennsylvania: {
    name: "Pennsylvania",
    abbreviation: "PA",
    slug: "pennsylvania",
    emoji: "🔔",
    lawName: "Breach of Personal Information Notification Act",
    lawYear: "2006",
    lawAcronym: "BPINA",
    badgeText: "Federal + State Protected",
    responseTimeDays: 30,
    maxFine: "Varies",
    population: "13M+",
    rights: FEDERAL_RIGHTS,
    topBrokers: BROKERS_SET_A,
    stats: federalStats("13M+", "400+"),
    faqs: federalFaqs("Pennsylvania"),
    heroDescription: "GhostMyData helps Pennsylvania residents remove their personal information from data brokers using federal privacy protections and the state's breach notification law.",
    ctaText: "Protect Your Pennsylvania Privacy Rights",
  },

  ohio: {
    name: "Ohio",
    abbreviation: "OH",
    slug: "ohio",
    emoji: "🌰",
    lawName: "Ohio Data Protection Act",
    lawYear: "2018",
    lawAcronym: "ODPA",
    badgeText: "Federal + State Protected",
    responseTimeDays: 30,
    maxFine: "Varies",
    population: "11M+",
    rights: FEDERAL_RIGHTS,
    topBrokers: BROKERS_SET_C,
    stats: federalStats("11M+", "350+"),
    faqs: [
      { question: "What privacy laws protect Ohio residents?", answer: "Ohio has the Ohio Data Protection Act (ODPA), which provides an affirmative defense to businesses that maintain cybersecurity programs. Ohio residents also benefit from federal protections under the FCRA, CAN-SPAM, and TCPA." },
      { question: "Can I remove my data from data brokers in Ohio?", answer: "Yes. You can submit opt-out requests to data brokers under federal law and broker policies. Most brokers honor removal requests regardless of your state of residence." },
      { question: "What is the Ohio Data Protection Act?", answer: "The ODPA incentivizes businesses to implement cybersecurity programs by providing a legal safe harbor. It doesn't give consumers direct privacy rights but encourages better data protection practices." },
      { question: "How long do data brokers have to respond in Ohio?", answer: "Under federal law (FCRA), data brokers must respond within 30 days. Most brokers process opt-out requests within 24 hours to 30 days." },
      { question: "Does Ohio have a data breach notification law?", answer: "Yes, Ohio requires businesses to notify residents of data breaches in a reasonable time. The state also has the ODPA encouraging strong cybersecurity practices." },
      { question: "How does GhostMyData help Ohio residents?", answer: "GhostMyData automates opt-out requests across 2,100+ data brokers, tracks responses, and continuously monitors for re-listings to keep your personal information private." },
    ],
    heroDescription: "GhostMyData helps Ohio residents remove their personal information from data brokers using federal and state privacy protections.",
    ctaText: "Protect Your Ohio Privacy Rights",
  },

  georgia: {
    name: "Georgia",
    abbreviation: "GA",
    slug: "georgia",
    emoji: "🍑",
    lawName: "Federal Privacy Protections",
    lawYear: "Various",
    lawAcronym: "Federal",
    badgeText: "Federal Protected",
    responseTimeDays: 30,
    maxFine: "Varies",
    population: "11M+",
    rights: FEDERAL_RIGHTS,
    topBrokers: BROKERS_SET_B,
    stats: federalStats("11M+", "350+"),
    faqs: federalFaqs("Georgia"),
    heroDescription: "GhostMyData helps Georgia residents remove their personal information from data brokers using federal privacy protections.",
    ctaText: "Protect Your Georgia Privacy Rights",
  },

  "north-carolina": {
    name: "North Carolina",
    abbreviation: "NC",
    slug: "north-carolina",
    emoji: "🌲",
    lawName: "Federal Privacy Protections",
    lawYear: "Various",
    lawAcronym: "Federal",
    badgeText: "Federal Protected",
    responseTimeDays: 30,
    maxFine: "Varies",
    population: "10M+",
    rights: FEDERAL_RIGHTS,
    topBrokers: BROKERS_SET_C,
    stats: federalStats("10M+", "350+"),
    faqs: federalFaqs("North Carolina"),
    heroDescription: "GhostMyData helps North Carolina residents remove their personal information from data brokers using federal privacy protections.",
    ctaText: "Protect Your North Carolina Privacy Rights",
  },

  michigan: {
    name: "Michigan",
    abbreviation: "MI",
    slug: "michigan",
    emoji: "🏔️",
    lawName: "Federal Privacy Protections",
    lawYear: "Various",
    lawAcronym: "Federal",
    badgeText: "Federal Protected",
    responseTimeDays: 30,
    maxFine: "Varies",
    population: "10M+",
    rights: FEDERAL_RIGHTS,
    topBrokers: BROKERS_SET_A,
    stats: federalStats("10M+", "350+"),
    faqs: federalFaqs("Michigan"),
    heroDescription: "GhostMyData helps Michigan residents remove their personal information from data brokers using federal privacy protections.",
    ctaText: "Protect Your Michigan Privacy Rights",
  },

  // ═══════════════════════════════════════════════════
  // STATES WITH COMPREHENSIVE PRIVACY LAWS
  // ═══════════════════════════════════════════════════
  virginia: {
    name: "Virginia",
    abbreviation: "VA",
    slug: "virginia",
    emoji: "🏛️",
    lawName: "Virginia Consumer Data Protection Act",
    lawYear: "2023",
    lawAcronym: "VCDPA",
    badgeText: "VCDPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "8.6M+",
    rights: [
      { title: "Right to Access", description: "Confirm whether a controller is processing your data and access that data" },
      { title: "Right to Delete", description: "Request deletion of personal data you've provided" },
      { title: "Right to Opt-Out", description: "Opt out of the sale of personal data, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Request correction of inaccurate personal data" },
    ],
    topBrokers: BROKERS_SET_B,
    stats: stateStats("8.6M+", "350+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the VCDPA?", answer: "The Virginia Consumer Data Protection Act (VCDPA), effective January 1, 2023, was the second comprehensive state privacy law after California's CCPA. It gives Virginia residents rights over their personal data." },
      { question: "Who does the VCDPA apply to?", answer: "The VCDPA applies to businesses that conduct business in Virginia or target Virginia residents, and that control or process data of 100,000+ consumers or 25,000+ consumers while deriving 50%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond to consumer requests within 45 days, with a possible 45-day extension." },
      { question: "Can I sue under the VCDPA?", answer: "No, the VCDPA does not include a private right of action. Only the Virginia Attorney General can enforce the law." },
      { question: "What makes VCDPA different from CCPA?", answer: "VCDPA uses an opt-in model for sensitive data processing, requires data protection assessments, and does not include a private right of action. It also has a narrower definition of 'sale' than CCPA." },
      { question: "How does GhostMyData help Virginia residents?", answer: "GhostMyData automates VCDPA-compliant deletion requests across 2,100+ data brokers, tracks the 45-day response window, and provides ongoing monitoring." },
    ],
    heroDescription: "Exercise your Virginia Consumer Data Protection Act (VCDPA) rights. GhostMyData helps Virginia residents remove their personal information from data brokers.",
    ctaText: "Protect Your Virginia Privacy Rights",
  },

  colorado: {
    name: "Colorado",
    abbreviation: "CO",
    slug: "colorado",
    emoji: "🏔️",
    lawName: "Colorado Privacy Act",
    lawYear: "2023",
    lawAcronym: "CPA",
    badgeText: "CPA Protected",
    responseTimeDays: 45,
    maxFine: "$20,000",
    population: "5.8M+",
    rights: [
      { title: "Right to Access", description: "Access the personal data a controller has collected about you" },
      { title: "Right to Delete", description: "Request deletion of your personal data" },
      { title: "Right to Opt-Out", description: "Opt out of targeted advertising, sale of data, and profiling" },
      { title: "Right to Portability", description: "Obtain your personal data in a portable, usable format" },
    ],
    topBrokers: BROKERS_SET_A,
    stats: stateStats("5.8M+", "350+", "$20,000", "45 Days"),
    faqs: [
      { question: "What is the Colorado Privacy Act?", answer: "The Colorado Privacy Act (CPA) took effect July 1, 2023. It provides Colorado residents with rights to access, correct, delete, and port their personal data, and to opt out of data sales and targeted advertising." },
      { question: "Who does the CPA apply to?", answer: "The CPA applies to entities conducting business in Colorado or targeting Colorado residents that control or process data of 100,000+ consumers per year, or 25,000+ consumers while deriving revenue from data sales." },
      { question: "What's unique about the Colorado Privacy Act?", answer: "Colorado's CPA requires a universal opt-out mechanism, meaning businesses must honor browser-based opt-out signals like Global Privacy Control (GPC)." },
      { question: "How long do companies have to respond?", answer: "Controllers must respond within 45 days, with one 45-day extension if reasonably necessary." },
      { question: "What penalties exist for CPA violations?", answer: "The Colorado Attorney General can impose civil penalties of up to $20,000 per violation. There is no private right of action." },
      { question: "How does GhostMyData help Colorado residents?", answer: "GhostMyData automates CPA-compliant deletion requests, tracks response deadlines, and continuously monitors data brokers for re-listings of your information." },
    ],
    heroDescription: "Exercise your Colorado Privacy Act rights. GhostMyData helps Colorado residents remove their personal information from data brokers.",
    ctaText: "Protect Your Colorado Privacy Rights",
  },

  connecticut: {
    name: "Connecticut",
    abbreviation: "CT",
    slug: "connecticut",
    emoji: "⚓",
    lawName: "Connecticut Data Privacy Act",
    lawYear: "2023",
    lawAcronym: "CTDPA",
    badgeText: "CTDPA Protected",
    responseTimeDays: 45,
    maxFine: "$5,000",
    population: "3.6M+",
    rights: [
      { title: "Right to Access", description: "Access your personal data and confirm it's being processed" },
      { title: "Right to Delete", description: "Request deletion of personal data provided by you or obtained about you" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccuracies in your personal data" },
    ],
    topBrokers: BROKERS_SET_C,
    stats: stateStats("3.6M+", "300+", "$5,000", "45 Days"),
    faqs: [
      { question: "What is the CTDPA?", answer: "The Connecticut Data Privacy Act (CTDPA) took effect July 1, 2023. It gives Connecticut residents comprehensive privacy rights including access, deletion, correction, and opt-out rights." },
      { question: "Who does the CTDPA apply to?", answer: "The CTDPA applies to entities conducting business in Connecticut or targeting Connecticut residents that control or process data of 100,000+ consumers or 25,000+ consumers while deriving 25%+ revenue from data sales." },
      { question: "Does Connecticut require universal opt-out?", answer: "Yes, starting January 1, 2025, businesses must honor universal opt-out mechanisms like Global Privacy Control (GPC)." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with one 45-day extension if reasonably necessary." },
      { question: "What penalties exist for violations?", answer: "The Connecticut Attorney General can impose civil penalties of up to $5,000 per willful violation under the Connecticut Unfair Trade Practices Act." },
      { question: "How does GhostMyData help Connecticut residents?", answer: "GhostMyData automates CTDPA-compliant deletion requests to 2,100+ data brokers and provides continuous monitoring for re-listings." },
    ],
    heroDescription: "Exercise your Connecticut Data Privacy Act (CTDPA) rights. GhostMyData helps Connecticut residents remove their personal information from data brokers.",
    ctaText: "Protect Your Connecticut Privacy Rights",
  },

  utah: {
    name: "Utah",
    abbreviation: "UT",
    slug: "utah",
    emoji: "🏜️",
    lawName: "Utah Consumer Privacy Act",
    lawYear: "2023",
    lawAcronym: "UCPA",
    badgeText: "UCPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "3.4M+",
    rights: [
      { title: "Right to Access", description: "Access the personal data a controller has collected about you" },
      { title: "Right to Delete", description: "Request deletion of personal data you've provided" },
      { title: "Right to Opt-Out", description: "Opt out of targeted advertising and sale of personal data" },
      { title: "Right to Portability", description: "Obtain a copy of your data in a portable format" },
    ],
    topBrokers: BROKERS_SET_B,
    stats: stateStats("3.4M+", "300+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the UCPA?", answer: "The Utah Consumer Privacy Act (UCPA) took effect December 31, 2023. It is considered the most business-friendly state privacy law, with higher applicability thresholds." },
      { question: "Who does the UCPA apply to?", answer: "The UCPA applies to businesses with annual revenue of $25M+ that conduct business in Utah or target Utah residents, and that control or process data of 100,000+ consumers or 25,000+ consumers while deriving 50%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with no extension provided." },
      { question: "Does the UCPA require data protection assessments?", answer: "No, unlike other state laws, the UCPA does not require data protection assessments or consent for sensitive data processing." },
      { question: "What penalties exist for violations?", answer: "The Utah Attorney General can impose civil penalties of up to $7,500 per violation after a 30-day cure period." },
      { question: "How does GhostMyData help Utah residents?", answer: "GhostMyData automates removal requests to data brokers across 2,100+ sites, tracks compliance, and monitors for re-listings to protect your privacy." },
    ],
    heroDescription: "Exercise your Utah Consumer Privacy Act (UCPA) rights. GhostMyData helps Utah residents remove their personal information from data brokers.",
    ctaText: "Protect Your Utah Privacy Rights",
  },

  iowa: {
    name: "Iowa",
    abbreviation: "IA",
    slug: "iowa",
    emoji: "🌽",
    lawName: "Iowa Consumer Data Protection Act",
    lawYear: "2025",
    lawAcronym: "ICDPA",
    badgeText: "ICDPA Protected",
    responseTimeDays: 90,
    maxFine: "$7,500",
    population: "3.2M+",
    rights: [
      { title: "Right to Access", description: "Confirm whether a controller is processing your data and access that data" },
      { title: "Right to Delete", description: "Request deletion of personal data you've provided" },
      { title: "Right to Opt-Out", description: "Opt out of targeted advertising, data sales, and profiling" },
      { title: "Right to Portability", description: "Obtain a copy of your data in a portable format" },
    ],
    topBrokers: BROKERS_SET_A,
    stats: stateStats("3.2M+", "300+", "$7,500", "90 Days"),
    faqs: [
      { question: "What is the ICDPA?", answer: "The Iowa Consumer Data Protection Act (ICDPA) takes effect January 1, 2025. It provides Iowa residents with rights to access, delete, and opt out of data processing." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 90 days — the longest response window of any state privacy law." },
      { question: "Who does the ICDPA apply to?", answer: "The ICDPA applies to businesses that control or process data of 100,000+ Iowa consumers or 25,000+ consumers while deriving 50%+ revenue from data sales." },
      { question: "Does Iowa include a right to correct data?", answer: "No, Iowa is one of the few state privacy laws that does not include a right to correction." },
      { question: "What penalties exist for violations?", answer: "The Iowa Attorney General can impose civil penalties of up to $7,500 per violation after a 90-day cure period." },
      { question: "How does GhostMyData help Iowa residents?", answer: "GhostMyData automates removal requests to 2,100+ data brokers, tracks the 90-day response window, and provides ongoing monitoring." },
    ],
    heroDescription: "Exercise your Iowa Consumer Data Protection Act (ICDPA) rights. GhostMyData helps Iowa residents remove their personal information from data brokers.",
    ctaText: "Protect Your Iowa Privacy Rights",
  },

  indiana: {
    name: "Indiana",
    abbreviation: "IN",
    slug: "indiana",
    emoji: "🏁",
    lawName: "Indiana Consumer Data Protection Act",
    lawYear: "2026",
    lawAcronym: "INCDPA",
    badgeText: "INCDPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "6.8M+",
    rights: [
      { title: "Right to Access", description: "Confirm processing and access your personal data" },
      { title: "Right to Delete", description: "Request deletion of personal data" },
      { title: "Right to Opt-Out", description: "Opt out of targeted advertising, data sales, and profiling" },
      { title: "Right to Correct", description: "Request correction of inaccurate personal data" },
    ],
    topBrokers: BROKERS_SET_C,
    stats: stateStats("6.8M+", "350+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the INCDPA?", answer: "The Indiana Consumer Data Protection Act (INCDPA) takes effect January 1, 2026. It provides Indiana residents with comprehensive data privacy rights." },
      { question: "Who does the INCDPA apply to?", answer: "The INCDPA applies to entities conducting business in Indiana that control or process data of 100,000+ consumers or 25,000+ consumers while deriving 50%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond to consumer requests within 45 days." },
      { question: "What rights do I have under INCDPA?", answer: "You have rights to access, correct, delete, and port your data, plus the right to opt out of data sales, targeted advertising, and profiling." },
      { question: "What penalties exist for violations?", answer: "The Indiana Attorney General can impose civil penalties of up to $7,500 per violation." },
      { question: "How does GhostMyData help Indiana residents?", answer: "GhostMyData automates INCDPA-compliant deletion requests to 2,100+ data brokers and provides continuous monitoring." },
    ],
    heroDescription: "Exercise your Indiana Consumer Data Protection Act (INCDPA) rights. GhostMyData helps Indiana residents remove personal information from data brokers.",
    ctaText: "Protect Your Indiana Privacy Rights",
  },

  tennessee: {
    name: "Tennessee",
    abbreviation: "TN",
    slug: "tennessee",
    emoji: "🎸",
    lawName: "Tennessee Information Protection Act",
    lawYear: "2025",
    lawAcronym: "TIPA",
    badgeText: "TIPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "7M+",
    rights: [
      { title: "Right to Access", description: "Access the personal information a controller has collected about you" },
      { title: "Right to Delete", description: "Request deletion of personal information" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccuracies in your personal information" },
    ],
    topBrokers: BROKERS_SET_B,
    stats: stateStats("7M+", "350+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is TIPA?", answer: "The Tennessee Information Protection Act (TIPA) takes effect July 1, 2025. It provides Tennessee residents with comprehensive data privacy rights modeled on Virginia's VCDPA." },
      { question: "Who does TIPA apply to?", answer: "TIPA applies to entities conducting business in Tennessee that control or process data of 175,000+ consumers or 25,000+ consumers while deriving 50%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with a possible 45-day extension." },
      { question: "What's unique about TIPA?", answer: "Tennessee's law includes an affirmative defense for businesses that comply with NIST privacy frameworks, incentivizing proactive data protection." },
      { question: "What penalties exist for violations?", answer: "The Tennessee Attorney General can impose civil penalties of up to $7,500 per violation after a 60-day cure period." },
      { question: "How does GhostMyData help Tennessee residents?", answer: "GhostMyData automates removal requests to 2,100+ data brokers, tracks TIPA deadlines, and provides ongoing monitoring for re-listings." },
    ],
    heroDescription: "Exercise your Tennessee Information Protection Act (TIPA) rights. GhostMyData helps Tennessee residents remove their personal information from data brokers.",
    ctaText: "Protect Your Tennessee Privacy Rights",
  },

  montana: {
    name: "Montana",
    abbreviation: "MT",
    slug: "montana",
    emoji: "🦌",
    lawName: "Montana Consumer Data Privacy Act",
    lawYear: "2024",
    lawAcronym: "MCDPA",
    badgeText: "MCDPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "1.1M+",
    rights: [
      { title: "Right to Access", description: "Access the personal data collected about you" },
      { title: "Right to Delete", description: "Request deletion of your personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccuracies in your personal data" },
    ],
    topBrokers: BROKERS_SET_A,
    stats: stateStats("1.1M+", "300+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the MCDPA?", answer: "The Montana Consumer Data Privacy Act (MCDPA) took effect October 1, 2024. It provides Montana residents with comprehensive data privacy rights." },
      { question: "Who does the MCDPA apply to?", answer: "The MCDPA applies to businesses conducting business in Montana that control or process data of 50,000+ consumers (lowest threshold in the US) or 25,000+ consumers while deriving 25%+ revenue from data sales." },
      { question: "What makes Montana's law notable?", answer: "Montana has the lowest consumer threshold (50,000) of any state privacy law, meaning more businesses must comply. This reflects Montana's smaller population." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with one 15-day extension." },
      { question: "What penalties exist for violations?", answer: "The Montana Attorney General can impose civil penalties of up to $7,500 per violation." },
      { question: "How does GhostMyData help Montana residents?", answer: "GhostMyData automates deletion requests to 2,100+ data brokers, tracks MCDPA deadlines, and monitors for re-listings." },
    ],
    heroDescription: "Exercise your Montana Consumer Data Privacy Act (MCDPA) rights. GhostMyData helps Montana residents remove their personal information from data brokers.",
    ctaText: "Protect Your Montana Privacy Rights",
  },

  oregon: {
    name: "Oregon",
    abbreviation: "OR",
    slug: "oregon",
    emoji: "🌲",
    lawName: "Oregon Consumer Privacy Act",
    lawYear: "2024",
    lawAcronym: "OCPA",
    badgeText: "OCPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "4.2M+",
    rights: [
      { title: "Right to Access", description: "Access your personal data held by controllers" },
      { title: "Right to Delete", description: "Request deletion of personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccurate personal data" },
    ],
    topBrokers: BROKERS_SET_C,
    stats: stateStats("4.2M+", "350+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the OCPA?", answer: "The Oregon Consumer Privacy Act (OCPA) took effect July 1, 2024. It provides comprehensive privacy rights to Oregon residents and applies to a broad range of businesses." },
      { question: "Who does the OCPA apply to?", answer: "The OCPA applies to businesses that control or process data of 100,000+ Oregon consumers, or 25,000+ consumers while deriving 25%+ revenue from data sales. Notably, it does not include a revenue threshold." },
      { question: "What makes Oregon's law unique?", answer: "Oregon's OCPA has no revenue threshold, applies to nonprofits, and includes a right to obtain a list of specific third parties to whom data was disclosed." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with one 45-day extension." },
      { question: "What penalties exist for violations?", answer: "The Oregon Attorney General can impose civil penalties of up to $7,500 per violation." },
      { question: "How does GhostMyData help Oregon residents?", answer: "GhostMyData automates OCPA-compliant removal requests to 2,100+ data brokers and provides ongoing monitoring." },
    ],
    heroDescription: "Exercise your Oregon Consumer Privacy Act (OCPA) rights. GhostMyData helps Oregon residents remove their personal information from data brokers.",
    ctaText: "Protect Your Oregon Privacy Rights",
  },

  delaware: {
    name: "Delaware",
    abbreviation: "DE",
    slug: "delaware",
    emoji: "💎",
    lawName: "Delaware Personal Data Privacy Act",
    lawYear: "2025",
    lawAcronym: "DPDPA",
    badgeText: "DPDPA Protected",
    responseTimeDays: 45,
    maxFine: "$10,000",
    population: "1M+",
    rights: [
      { title: "Right to Access", description: "Access personal data collected about you" },
      { title: "Right to Delete", description: "Request deletion of your personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccuracies in your personal data" },
    ],
    topBrokers: BROKERS_SET_B,
    stats: stateStats("1M+", "300+", "$10,000", "45 Days"),
    faqs: [
      { question: "What is the DPDPA?", answer: "The Delaware Personal Data Privacy Act (DPDPA) takes effect January 1, 2025. It provides broad consumer privacy protections with relatively low applicability thresholds." },
      { question: "Who does the DPDPA apply to?", answer: "The DPDPA applies to entities that control or process data of 35,000+ Delaware consumers or 10,000+ consumers while deriving 20%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with one 45-day extension if reasonably necessary." },
      { question: "What penalties exist for violations?", answer: "The Delaware Attorney General can impose civil penalties of up to $10,000 per violation." },
      { question: "What makes Delaware's law notable?", answer: "Delaware's DPDPA has one of the lowest consumer thresholds (35,000) and includes provisions for universal opt-out mechanisms." },
      { question: "How does GhostMyData help Delaware residents?", answer: "GhostMyData automates removal requests to 2,100+ data brokers, tracks DPDPA deadlines, and monitors for re-listings." },
    ],
    heroDescription: "Exercise your Delaware Personal Data Privacy Act (DPDPA) rights. GhostMyData helps Delaware residents remove their personal information from data brokers.",
    ctaText: "Protect Your Delaware Privacy Rights",
  },

  "new-hampshire": {
    name: "New Hampshire",
    abbreviation: "NH",
    slug: "new-hampshire",
    emoji: "🏔️",
    lawName: "New Hampshire Privacy Act",
    lawYear: "2025",
    lawAcronym: "NHPA",
    badgeText: "NHPA Protected",
    responseTimeDays: 45,
    maxFine: "$10,000",
    population: "1.4M+",
    rights: [
      { title: "Right to Access", description: "Access personal data collected about you" },
      { title: "Right to Delete", description: "Request deletion of personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Request correction of inaccurate personal data" },
    ],
    topBrokers: BROKERS_SET_A,
    stats: stateStats("1.4M+", "300+", "$10,000", "45 Days"),
    faqs: [
      { question: "What is the NHPA?", answer: "The New Hampshire Privacy Act (NHPA) takes effect January 1, 2025. It gives residents comprehensive privacy rights including access, deletion, and opt-out of data sales." },
      { question: "Who does the NHPA apply to?", answer: "The NHPA applies to entities conducting business in New Hampshire that control or process data of 35,000+ consumers or 10,000+ consumers while deriving 25%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with a possible 45-day extension." },
      { question: "What penalties exist for violations?", answer: "The New Hampshire Attorney General can impose civil penalties of up to $10,000 per violation." },
      { question: "Does New Hampshire require universal opt-out?", answer: "Yes, the NHPA requires businesses to honor universal opt-out mechanisms like Global Privacy Control (GPC)." },
      { question: "How does GhostMyData help New Hampshire residents?", answer: "GhostMyData automates deletion requests to 2,100+ data brokers and provides ongoing monitoring for re-listings." },
    ],
    heroDescription: "Exercise your New Hampshire Privacy Act (NHPA) rights. GhostMyData helps New Hampshire residents remove personal information from data brokers.",
    ctaText: "Protect Your New Hampshire Privacy Rights",
  },

  "new-jersey": {
    name: "New Jersey",
    abbreviation: "NJ",
    slug: "new-jersey",
    emoji: "🏖️",
    lawName: "New Jersey Data Privacy Act",
    lawYear: "2025",
    lawAcronym: "NJDPA",
    badgeText: "NJDPA Protected",
    responseTimeDays: 45,
    maxFine: "$10,000",
    population: "9.3M+",
    rights: [
      { title: "Right to Access", description: "Access personal data a controller has collected about you" },
      { title: "Right to Delete", description: "Request deletion of your personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccuracies in your personal data" },
    ],
    topBrokers: BROKERS_SET_C,
    stats: stateStats("9.3M+", "400+", "$10,000", "45 Days"),
    faqs: [
      { question: "What is the NJDPA?", answer: "The New Jersey Data Privacy Act (NJDPA) takes effect January 15, 2025. It provides comprehensive privacy rights to New Jersey residents." },
      { question: "Who does the NJDPA apply to?", answer: "The NJDPA applies to entities that control or process data of 100,000+ New Jersey consumers or 25,000+ consumers while deriving revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with a possible 45-day extension." },
      { question: "What makes New Jersey's law notable?", answer: "The NJDPA includes strong protections for health data and financial data, and requires recognition of universal opt-out mechanisms." },
      { question: "What penalties exist for violations?", answer: "The New Jersey Attorney General can impose penalties up to $10,000 per first offense and $20,000 per subsequent offense under the Consumer Fraud Act." },
      { question: "How does GhostMyData help New Jersey residents?", answer: "GhostMyData automates NJDPA-compliant deletion requests to 2,100+ data brokers and provides continuous monitoring." },
    ],
    heroDescription: "Exercise your New Jersey Data Privacy Act (NJDPA) rights. GhostMyData helps New Jersey residents remove personal information from data brokers.",
    ctaText: "Protect Your New Jersey Privacy Rights",
  },

  kentucky: {
    name: "Kentucky",
    abbreviation: "KY",
    slug: "kentucky",
    emoji: "🐴",
    lawName: "Kentucky Consumer Data Protection Act",
    lawYear: "2026",
    lawAcronym: "KCDPA",
    badgeText: "KCDPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "4.5M+",
    rights: [
      { title: "Right to Access", description: "Access personal data collected about you" },
      { title: "Right to Delete", description: "Request deletion of personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccurate personal data" },
    ],
    topBrokers: BROKERS_SET_B,
    stats: stateStats("4.5M+", "300+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the KCDPA?", answer: "The Kentucky Consumer Data Protection Act (KCDPA) takes effect January 1, 2026. It provides comprehensive privacy rights modeled on Virginia's VCDPA." },
      { question: "Who does the KCDPA apply to?", answer: "The KCDPA applies to entities conducting business in Kentucky that control or process data of 100,000+ consumers or 25,000+ consumers while deriving 50%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days, with a possible 45-day extension." },
      { question: "What penalties exist for violations?", answer: "The Kentucky Attorney General can impose civil penalties of up to $7,500 per violation after a 30-day cure period." },
      { question: "What rights do I have under KCDPA?", answer: "You have rights to access, correct, delete, and port your data, plus the right to opt out of data sales and targeted advertising." },
      { question: "How does GhostMyData help Kentucky residents?", answer: "GhostMyData automates removal requests to 2,100+ data brokers and provides monitoring to protect your data." },
    ],
    heroDescription: "Exercise your Kentucky Consumer Data Protection Act (KCDPA) rights. GhostMyData helps Kentucky residents remove personal information from data brokers.",
    ctaText: "Protect Your Kentucky Privacy Rights",
  },

  nebraska: {
    name: "Nebraska",
    abbreviation: "NE",
    slug: "nebraska",
    emoji: "🌾",
    lawName: "Nebraska Data Privacy Act",
    lawYear: "2025",
    lawAcronym: "NDPA",
    badgeText: "NDPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "2M+",
    rights: [
      { title: "Right to Access", description: "Access personal data a controller has collected" },
      { title: "Right to Delete", description: "Request deletion of your personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales and targeted advertising" },
      { title: "Right to Correct", description: "Correct inaccuracies in your data" },
    ],
    topBrokers: BROKERS_SET_A,
    stats: stateStats("2M+", "300+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the NDPA?", answer: "The Nebraska Data Privacy Act (NDPA) takes effect January 1, 2025. It applies to all businesses in Nebraska without revenue or processing thresholds." },
      { question: "What makes Nebraska's law unique?", answer: "Nebraska's NDPA applies to all entities conducting business in the state regardless of size — one of the broadest applicability scopes of any state privacy law." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days." },
      { question: "What penalties exist for violations?", answer: "The Nebraska Attorney General can impose penalties of up to $7,500 per violation under the Consumer Protection Act." },
      { question: "Does the NDPA have a cure period?", answer: "Yes, the NDPA includes a 30-day cure period before enforcement action." },
      { question: "How does GhostMyData help Nebraska residents?", answer: "GhostMyData automates removal requests to 2,100+ data brokers, tracks NDPA deadlines, and monitors for re-listings." },
    ],
    heroDescription: "Exercise your Nebraska Data Privacy Act (NDPA) rights. GhostMyData helps Nebraska residents remove personal information from data brokers.",
    ctaText: "Protect Your Nebraska Privacy Rights",
  },

  maryland: {
    name: "Maryland",
    abbreviation: "MD",
    slug: "maryland",
    emoji: "🦀",
    lawName: "Maryland Online Data Privacy Act",
    lawYear: "2025",
    lawAcronym: "MODPA",
    badgeText: "MODPA Protected",
    responseTimeDays: 45,
    maxFine: "$10,000",
    population: "6.2M+",
    rights: [
      { title: "Right to Access", description: "Access personal data collected about you" },
      { title: "Right to Delete", description: "Request deletion of your personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales and targeted advertising" },
      { title: "Right to Correct", description: "Correct inaccurate personal data" },
    ],
    topBrokers: BROKERS_SET_C,
    stats: stateStats("6.2M+", "350+", "$10,000", "45 Days"),
    faqs: [
      { question: "What is the MODPA?", answer: "The Maryland Online Data Privacy Act (MODPA) takes effect October 1, 2025. It is one of the strongest state privacy laws, restricting data collection to what is necessary for the service provided." },
      { question: "What makes Maryland's law notable?", answer: "MODPA introduces a data minimization requirement — businesses can only collect data that is reasonably necessary. It also prohibits the sale of sensitive data entirely." },
      { question: "Who does the MODPA apply to?", answer: "The MODPA applies to entities that control or process data of 35,000+ Maryland consumers or 10,000+ consumers while deriving 20%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days." },
      { question: "What penalties exist for violations?", answer: "The Maryland Attorney General can impose penalties up to $10,000 per violation under the Consumer Protection Act." },
      { question: "How does GhostMyData help Maryland residents?", answer: "GhostMyData automates MODPA-compliant removal requests to 2,100+ data brokers and provides continuous monitoring." },
    ],
    heroDescription: "Exercise your Maryland Online Data Privacy Act (MODPA) rights. GhostMyData helps Maryland residents remove personal information from data brokers.",
    ctaText: "Protect Your Maryland Privacy Rights",
  },

  minnesota: {
    name: "Minnesota",
    abbreviation: "MN",
    slug: "minnesota",
    emoji: "❄️",
    lawName: "Minnesota Consumer Data Privacy Act",
    lawYear: "2025",
    lawAcronym: "MNCDPA",
    badgeText: "MNCDPA Protected",
    responseTimeDays: 45,
    maxFine: "$7,500",
    population: "5.7M+",
    rights: [
      { title: "Right to Access", description: "Access personal data collected about you" },
      { title: "Right to Delete", description: "Request deletion of personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccuracies in your personal data" },
    ],
    topBrokers: BROKERS_SET_B,
    stats: stateStats("5.7M+", "350+", "$7,500", "45 Days"),
    faqs: [
      { question: "What is the MNCDPA?", answer: "The Minnesota Consumer Data Privacy Act (MNCDPA) takes effect July 31, 2025. It provides broad consumer privacy protections for Minnesota residents." },
      { question: "What makes Minnesota's law unique?", answer: "The MNCDPA includes a private right of action for certain violations and requires data protection assessments for high-risk processing activities." },
      { question: "Who does the MNCDPA apply to?", answer: "The MNCDPA applies to entities that conduct business in Minnesota and control or process data of 100,000+ consumers or 25,000+ consumers while deriving 25%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days." },
      { question: "What penalties exist for violations?", answer: "The Minnesota Attorney General can impose penalties up to $7,500 per violation, and consumers may have limited private right of action." },
      { question: "How does GhostMyData help Minnesota residents?", answer: "GhostMyData automates deletion requests to 2,100+ data brokers and provides ongoing monitoring for re-listings." },
    ],
    heroDescription: "Exercise your Minnesota Consumer Data Privacy Act (MNCDPA) rights. GhostMyData helps Minnesota residents remove personal information from data brokers.",
    ctaText: "Protect Your Minnesota Privacy Rights",
  },

  "rhode-island": {
    name: "Rhode Island",
    abbreviation: "RI",
    slug: "rhode-island",
    emoji: "⚓",
    lawName: "Rhode Island Data Transparency and Privacy Protection Act",
    lawYear: "2026",
    lawAcronym: "RIDPA",
    badgeText: "RIDPA Protected",
    responseTimeDays: 45,
    maxFine: "$10,000",
    population: "1.1M+",
    rights: [
      { title: "Right to Access", description: "Access personal data collected about you" },
      { title: "Right to Delete", description: "Request deletion of personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales, targeted advertising, and profiling" },
      { title: "Right to Correct", description: "Correct inaccuracies in your personal data" },
    ],
    topBrokers: BROKERS_SET_A,
    stats: stateStats("1.1M+", "300+", "$10,000", "45 Days"),
    faqs: [
      { question: "What is the RIDPA?", answer: "The Rhode Island Data Transparency and Privacy Protection Act (RIDPA) takes effect January 1, 2026. It provides comprehensive data privacy rights to Rhode Island residents." },
      { question: "Who does the RIDPA apply to?", answer: "The RIDPA applies to entities conducting business in Rhode Island that control or process data of 35,000+ consumers or 10,000+ consumers while deriving 20%+ revenue from data sales." },
      { question: "How long do companies have to respond?", answer: "Companies must respond to consumer requests within 45 days." },
      { question: "What penalties exist for violations?", answer: "The Rhode Island Attorney General can impose penalties up to $10,000 per violation." },
      { question: "What rights do I have?", answer: "You have rights to access, correct, delete, and port your data, plus opt-out of data sales and targeted advertising." },
      { question: "How does GhostMyData help Rhode Island residents?", answer: "GhostMyData automates removal requests to 2,100+ data brokers and provides continuous monitoring for data re-listings." },
    ],
    heroDescription: "Exercise your Rhode Island Data Privacy Act rights. GhostMyData helps Rhode Island residents remove personal information from data brokers.",
    ctaText: "Protect Your Rhode Island Privacy Rights",
  },

  vermont: {
    name: "Vermont",
    abbreviation: "VT",
    slug: "vermont",
    emoji: "🍁",
    lawName: "Vermont Data Privacy Act",
    lawYear: "2025",
    lawAcronym: "VDPA",
    badgeText: "VDPA Protected",
    responseTimeDays: 45,
    maxFine: "$10,000",
    population: "650K+",
    rights: [
      { title: "Right to Access", description: "Access personal data held about you" },
      { title: "Right to Delete", description: "Request deletion of personal data" },
      { title: "Right to Opt-Out", description: "Opt out of data sales and targeted advertising" },
      { title: "Right to Sue", description: "Vermont provides a private right of action for certain privacy violations" },
    ],
    topBrokers: BROKERS_SET_C,
    stats: stateStats("650K+", "300+", "$10,000", "45 Days"),
    faqs: [
      { question: "What is the VDPA?", answer: "The Vermont Data Privacy Act (VDPA) takes effect July 1, 2025. Vermont has long been a leader in data broker regulation, requiring brokers to register with the state since 2018." },
      { question: "What makes Vermont's law unique?", answer: "Vermont was the first state to require data broker registration and includes a private right of action, allowing consumers to sue for violations." },
      { question: "Who does the VDPA apply to?", answer: "The VDPA applies broadly to entities conducting business in Vermont that collect personal data." },
      { question: "How long do companies have to respond?", answer: "Companies must respond within 45 days." },
      { question: "Can I sue data brokers in Vermont?", answer: "Yes, the VDPA includes a private right of action, making Vermont one of few states where consumers can sue directly for privacy violations." },
      { question: "How does GhostMyData help Vermont residents?", answer: "GhostMyData automates removal requests to 2,100+ data brokers, taking advantage of Vermont's strong data broker registration requirements." },
    ],
    heroDescription: "Exercise your Vermont Data Privacy Act (VDPA) rights. GhostMyData helps Vermont residents remove personal information from data brokers.",
    ctaText: "Protect Your Vermont Privacy Rights",
  },

  // ═══════════════════════════════════════════════════
  // REMAINING STATES (Federal protections only)
  // ═══════════════════════════════════════════════════
  alabama: { name: "Alabama", abbreviation: "AL", slug: "alabama", emoji: "🌺", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "5.1M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_B, stats: federalStats("5.1M+", "350+"), faqs: federalFaqs("Alabama"), heroDescription: "GhostMyData helps Alabama residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Alabama Privacy Rights" },

  alaska: { name: "Alaska", abbreviation: "AK", slug: "alaska", emoji: "🐻‍❄️", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "730K+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_A, stats: federalStats("730K+", "300+"), faqs: federalFaqs("Alaska"), heroDescription: "GhostMyData helps Alaska residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Alaska Privacy Rights" },

  arizona: { name: "Arizona", abbreviation: "AZ", slug: "arizona", emoji: "🌵", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "7.4M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_C, stats: federalStats("7.4M+", "400+"), faqs: federalFaqs("Arizona"), heroDescription: "GhostMyData helps Arizona residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Arizona Privacy Rights" },

  arkansas: { name: "Arkansas", abbreviation: "AR", slug: "arkansas", emoji: "💎", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "3.1M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_B, stats: federalStats("3.1M+", "300+"), faqs: federalFaqs("Arkansas"), heroDescription: "GhostMyData helps Arkansas residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Arkansas Privacy Rights" },

  hawaii: { name: "Hawaii", abbreviation: "HI", slug: "hawaii", emoji: "🌺", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "1.4M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_A, stats: federalStats("1.4M+", "300+"), faqs: federalFaqs("Hawaii"), heroDescription: "GhostMyData helps Hawaii residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Hawaii Privacy Rights" },

  idaho: { name: "Idaho", abbreviation: "ID", slug: "idaho", emoji: "🥔", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "1.9M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_C, stats: federalStats("1.9M+", "300+"), faqs: federalFaqs("Idaho"), heroDescription: "GhostMyData helps Idaho residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Idaho Privacy Rights" },

  kansas: { name: "Kansas", abbreviation: "KS", slug: "kansas", emoji: "🌻", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "2.9M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_B, stats: federalStats("2.9M+", "300+"), faqs: federalFaqs("Kansas"), heroDescription: "GhostMyData helps Kansas residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Kansas Privacy Rights" },

  louisiana: { name: "Louisiana", abbreviation: "LA", slug: "louisiana", emoji: "⚜️", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "4.6M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_A, stats: federalStats("4.6M+", "350+"), faqs: federalFaqs("Louisiana"), heroDescription: "GhostMyData helps Louisiana residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Louisiana Privacy Rights" },

  maine: { name: "Maine", abbreviation: "ME", slug: "maine", emoji: "🦞", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "1.4M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_C, stats: federalStats("1.4M+", "300+"), faqs: federalFaqs("Maine"), heroDescription: "GhostMyData helps Maine residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Maine Privacy Rights" },

  massachusetts: { name: "Massachusetts", abbreviation: "MA", slug: "massachusetts", emoji: "🏛️", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "7M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_B, stats: federalStats("7M+", "400+"), faqs: federalFaqs("Massachusetts"), heroDescription: "GhostMyData helps Massachusetts residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Massachusetts Privacy Rights" },

  mississippi: { name: "Mississippi", abbreviation: "MS", slug: "mississippi", emoji: "🌊", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "2.9M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_A, stats: federalStats("2.9M+", "300+"), faqs: federalFaqs("Mississippi"), heroDescription: "GhostMyData helps Mississippi residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Mississippi Privacy Rights" },

  missouri: { name: "Missouri", abbreviation: "MO", slug: "missouri", emoji: "🏹", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "6.2M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_C, stats: federalStats("6.2M+", "350+"), faqs: federalFaqs("Missouri"), heroDescription: "GhostMyData helps Missouri residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Missouri Privacy Rights" },

  nevada: { name: "Nevada", abbreviation: "NV", slug: "nevada", emoji: "🎰", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "3.2M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_B, stats: federalStats("3.2M+", "350+"), faqs: federalFaqs("Nevada"), heroDescription: "GhostMyData helps Nevada residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Nevada Privacy Rights" },

  "new-mexico": { name: "New Mexico", abbreviation: "NM", slug: "new-mexico", emoji: "🌶️", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "2.1M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_A, stats: federalStats("2.1M+", "300+"), faqs: federalFaqs("New Mexico"), heroDescription: "GhostMyData helps New Mexico residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your New Mexico Privacy Rights" },

  "north-dakota": { name: "North Dakota", abbreviation: "ND", slug: "north-dakota", emoji: "🌾", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "780K+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_C, stats: federalStats("780K+", "300+"), faqs: federalFaqs("North Dakota"), heroDescription: "GhostMyData helps North Dakota residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your North Dakota Privacy Rights" },

  oklahoma: { name: "Oklahoma", abbreviation: "OK", slug: "oklahoma", emoji: "🌪️", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "4M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_B, stats: federalStats("4M+", "350+"), faqs: federalFaqs("Oklahoma"), heroDescription: "GhostMyData helps Oklahoma residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Oklahoma Privacy Rights" },

  "south-carolina": { name: "South Carolina", abbreviation: "SC", slug: "south-carolina", emoji: "🌴", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "5.3M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_A, stats: federalStats("5.3M+", "350+"), faqs: federalFaqs("South Carolina"), heroDescription: "GhostMyData helps South Carolina residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your South Carolina Privacy Rights" },

  "south-dakota": { name: "South Dakota", abbreviation: "SD", slug: "south-dakota", emoji: "🗿", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "900K+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_C, stats: federalStats("900K+", "300+"), faqs: federalFaqs("South Dakota"), heroDescription: "GhostMyData helps South Dakota residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your South Dakota Privacy Rights" },

  washington: { name: "Washington", abbreviation: "WA", slug: "washington", emoji: "🌲", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "7.8M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_B, stats: federalStats("7.8M+", "400+"), faqs: federalFaqs("Washington"), heroDescription: "GhostMyData helps Washington residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Washington Privacy Rights" },

  "west-virginia": { name: "West Virginia", abbreviation: "WV", slug: "west-virginia", emoji: "⛰️", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "1.8M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_A, stats: federalStats("1.8M+", "300+"), faqs: federalFaqs("West Virginia"), heroDescription: "GhostMyData helps West Virginia residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your West Virginia Privacy Rights" },

  wisconsin: { name: "Wisconsin", abbreviation: "WI", slug: "wisconsin", emoji: "🧀", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "5.9M+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_C, stats: federalStats("5.9M+", "350+"), faqs: federalFaqs("Wisconsin"), heroDescription: "GhostMyData helps Wisconsin residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Wisconsin Privacy Rights" },

  wyoming: { name: "Wyoming", abbreviation: "WY", slug: "wyoming", emoji: "🤠", lawName: "Federal Privacy Protections", lawYear: "Various", lawAcronym: "Federal", badgeText: "Federal Protected", responseTimeDays: 30, maxFine: "Varies", population: "580K+", rights: FEDERAL_RIGHTS, topBrokers: BROKERS_SET_B, stats: federalStats("580K+", "300+"), faqs: federalFaqs("Wyoming"), heroDescription: "GhostMyData helps Wyoming residents remove their personal information from data brokers using federal privacy protections.", ctaText: "Protect Your Wyoming Privacy Rights" },
};

export function getAllStateSlugs(): string[] {
  return Object.keys(STATE_DATA);
}
